name: My-Flow-1

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome Message
          run: echo "Please update the Laptop"
        - name: Checkout Started
          uses: actions/checkout@v4
        - name: List Files
          run: ls
        - name: ReadFile
          run: cat README.md
        
