name: My-Flow-1

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome Message
          run: echo "Please update the Laptop"
        - name: Checkout Started
          uses: actions/checkout@v4
        - name: Pipe Commands
          run: |
            ls
            cat README.md

            sudo apt install go -y

            go run main.go
